import Foundation

enum RoutineIconColorCatalog {
    static let icons: [String] = [
        "house.fill",
        "bolt.fill",
        "flame.fill",
        "leaf.fill",
        "heart.fill",
        "star.fill",
        "moon.fill",
        "sun.max.fill",
        "sparkles",
        "timer",
        "clock.fill",
        "bell.fill",
        "book.fill",
        "pencil",
        "graduationcap.fill",
        "briefcase.fill",
        "list.bullet",
        "checklist",
        "target",
        "figure.walk",
        "figure.run",
        "figure.mind.and.body",
        "figure.cooldown",
        "dumbbell.fill",
        "bed.double.fill",
        "cup.and.saucer.fill",
        "fork.knife",
        "music.note",
        "headphones",
        "gamecontroller.fill",
        "camera.fill",
        "globe",
        "location.fill",
        "wifi",
        "lock.fill",
        "shield.fill",
        "hand.raised.fill",
        "message.fill",
        "brain.head.profile",
        "hands.sparkles",
        "airplane",
        "car.fill",
        "bicycle",
        "paintbrush.fill",
        "hammer.fill",
        "wrench.and.screwdriver.fill",
        "leaf.arrow.circlepath",
        "drop.fill",
        "flag.fill",
        "gift.fill"
    ]

    static let colors: [String] = [
        // Neutrals
        "#8E8E93",
        "#636366",
        "#48484A",
        "#3A3A3C",
        "#2C2C2E",
        "#1C1C1E",
        "#AEAEB2",
        "#C7C7CC",
        // Accents
        "#FF3B30",
        "#FF9500",
        "#FFCC00",
        "#34C759",
        "#00C7BE",
        "#30B0C7",
        "#32ADE6",
        "#007AFF",
        "#0A84FF",
        "#5856D6",
        "#5E5CE6",
        "#AF52DE",
        "#BF5AF2",
        "#FF2D55"
    ]
}
